[common]
synced_files = []

[[profiles]]
name = "default"
synced_files = [
    ".config/fish",
    ".config/starship.toml",
    ".config/superfile",
    ".config/zellij",
    ".local/bin/dotstate",
    ".local/bin/zellij",
]
packages = []
